### PR TITLE
Forked and updated themes without GH releases for inclusion here.

### PR DESCRIPTION
**Pull request by xthursdayx**
I forked all of the themes causing problems due to not having GH releases, updated and standardized their file structure and code to match the current SN ext formatting and created tagged releases. I've created PRs with the maintainers to see if they want to merge my changes and if they do, I will update the theme extension `yaml` files in this repo accordingly so that they're attributed to their original maintainers. However, for now, this PR should fix the problems that existed with the themes that didn't have tagged releases. Cheers!

### CODE REVIEW

**Comment by xthursdayx** [comment]
Sorry, massively switched up this PR. Now it should allow for the inclusion of those themes that were causing problems.

**Comment by xthursdayx** [comment]
Please don't merge yet, I need to update to repos whose maintainers have merged my PRs. Will update ASAP and confirm here when this PR is ready to be merged. Cheers!

**Comment by gyaneesh** [comment]
Is this still open? Sorry had to step away for a bit.

**Comment by xthursdayx** [comment]
> Is this still open? Sorry had to step away for a bit.

Sorry, yes, I've been away, but will try to finish this up this weekend. It's mostly complete, I just need to check a couple of remaining themes.

**Comment by xthursdayx** [comment]
Sorry again for the delay. This PR is ready to be merged.

**Comment by xthursdayx** [comment]
Looks like two of the other commits that were merged conflict with changes in this PR. I think my version of `dark-hybrid-theme.yaml` should probably be prioritized since the repo referenced in the other PR no longer exists. The `vs-code-theme.yaml`is correct as the update was by the maintainer of that repo.

**Comment by xthursdayx** [comment]
Once this PR is merged I have two other PRs to submit - one for additional extensions and one for more themes.

**Comment by gyaneesh** [comment]
> Looks like two of the other commits that were merged conflict with changes in this PR. I think my version of `dark-hybrid-theme.yaml` should probably be prioritized since the repo referenced in the other PR no longer exists. The `vs-code-theme.yaml`is correct as the update was by the maintainer of that repo.

that's correct! I created a PR against your branch, if you approve that, this PR's conflict should resolve.

**Comment by xthursdayx** [comment]
> that's correct! I created a PR against your branch, if you approve that, this PR's conflict should resolve.

Done! I'll post the two additional PRs later today or tomorrow so you can check them out.

**Comment by gyaneesh** [comment]
> > that's correct! I created a PR against your branch, if you approve that, this PR's conflict should resolve.
> 
> Done! I'll post the two additional PRs later today or tomorrow so you can check them out.

Oh man, at this rate I'll need to hire a reviewer! /s

Thanks!

**Comment by xthursdayx** [comment]
> Oh man, at this rate I'll need to hire a reviewer! /s

Feel free to take your time reviewing them! No rush. I just figured I'd pull in all the themes and extensions that are still being updated.

**Pull request merged**
