### PR TITLE
Update NGINX snippet

### PR DESCRIPTION
**Pull request by xthursdayx**
Standard Notes now uses additional headers when grabbing extensions, so the NGINX `Access-Control-Allow-Headers` header needs to be updated.

### CODE REVIEW

**Comment by gyaneesh** [comment]
> Standard Notes now uses additional headers when grabbing extensions, so the NGINX `Access-Control-Allow-Headers` header needs to be updated.

Hey! Do you think you could link me to the change where this was introduced? Much appreciated!

**Comment by xthursdayx** [comment]
I haven't seen it posted anywhere by the SN folks. I just noticed the change when I was re-adding some forked versions of the Standard Notes editors (e.g. Simple Task Manager, Code-Editor, etc) to Standard Notes (both Desktop and Web) in order to try to figure out why the Subscription notice/read-only mode is being activated for self-hosted extensions. You can see the CORS error in this screenshot from the Developer Tools console from when I was trying to add my self-hosted version of Code-Editor to my self-hosted instance of Standard Notes Web:
Screen Shot 2021-12-02 at 00 51 30

**Comment by xthursdayx** [comment]
The change came from this commit https://github.com/standardnotes/snjs/commit/39f59ba69be8c50897284886581f79888e110d84 which was part of this PR: https://github.com/standardnotes/snjs/pull/400 with the change being to this file: https://github.com/standardnotes/snjs/blob/master/packages/snjs/lib/services/api/http_service.ts

**Comment by xthursdayx** [comment]
By  the way, I'm not seeing any CORS errors after having added those lines to my NGINX conf.

**Comment by andreipoe** [comment]
Hey @iganeshk I can confirm that I was getting the same header error with the instructions in the README, and after adding the changes in this PR I can load extensions successfully. Thanks @xthursdayx!

**Pull request merged**
