### PR TITLE
Change SN extension IDs

### PR DESCRIPTION
**Pull request by xthursdayx**
As discussed here:https://github.com/iganeshk/standardnotes-extensions/issues/33 and here:https://github.com/standardnotes/desktop/issues/789, there is now an issue with Standard Notes that causes Standard Notes Web, Desktop and Mobile to prevent non-subscription users from using editors (and eventually other extensions) developed and maintained by Standard Notes even when they are self-hosted. [One of the SN devs explained](https://github.com/standardnotes/desktop/issues/789#issuecomment-984716573) that this is because SN looks at the extension ID (e.g. id: org.standardnotes.bold-editor) and limits access to all extensions with IDs that begin with `org.standardnotes`. I've tested options for working around this issue, including forking their extension repositories and changing the IDs in the self-hosted extension builder, as well as just changing the IDs without forking the repos. Both result in working extensions, but since the latter is the easier option, this PR includes changes to change only the extension IDs of the StandardNotes core editors and other extensions.

### CODE REVIEW

**Comment by gclves** [comment]
Would this qualify as "repackaging" or "redistributing" changes? If so, it seems that some extensions (eg: TokenVault) do not allow that. From the thread you linked:

> Note that TokenVault does not have a redistribution license so repackaging that and redistributing it to other users is not fair use.

Mostly, though: thank you for this! The recent client changes have broken quite a few of my extensions, and your write-up has allowed me to work around the issues for the editors I care about most.

**Comment by andreipoe** [comment]
Hey, is this change still working for you? I've tried it on a new install and I'm getting the subscription errors.

**Comment by xthursdayx** [comment]
> Would this qualify as "repackaging" or "redistributing" changes? If so, it seems that some extensions (eg: TokenVault) do not allow that. From the thread you linked:
> 
> > Note that TokenVault does not have a redistribution license so repackaging that and redistributing it to other users is not fair use.
> 
> Mostly, though: thank you for this! The recent client changes have broken quite a few of my extensions, and your write-up has allowed me to work around the issues for the editors I care about most.

My sense was that changing the internal extension IDs used by the Standard Notes extension manager wouldn't count as repackaging or redistribution, since the code for the SN-developed extensions (such as TokenVault) is still being pulled from their own repos at runtime. None of their code is actually being repackaged or redistributed; the only change is ID that Standard Notes uses to identify each extension after they are pulled for you to self-host. 

I could be wrong about this, but it seemed to still fall within fair use, since at the end of the day the user (or this container on behalf of the user) will be pulling the extension code from SN's github repo to use the extensions privately.  If I'm mistaken though, I'm willing to remove TokenVault from the repo and let people just add it to their local code independently.

**Comment by xthursdayx** [comment]
> Hey, is this change still working for you? I've tried it on a new install and I'm getting the subscription errors.

Do you mean that you manually added the changes included in this PR and are still seeing subscription errors? The changes still seem to be working fine for me, so I'm not sure why that would be the case. Did you make sure to delete all local Standard Notes extension data from any machine running SN Web or Desktop, as well as the `extensions` created by this container on your webserver, before creating your new SN extensions container and adding the new extension `URLs`? If not, you may need to go through and delete each extension in Standard Notes Web or Desktop, delete your `server.ltd/extensions` directory, and rebuild and start your SN Extensions container (with the update extension IDs) before adding the new `URLs`. As you probably noticed, unfortunately, due to some changes to Standard Notes Desktop and Web, you now have to add each extension URL individually rather than just being able to add the URL for the `index.json` as the README states. Once this PR is merged I will update the README as well. 

Let me know if you've tried the steps I mentioned and are still seeing problems.

**Comment by andreipoe** [comment]
Thanks for your reply. Yes, I know the PR hasn't been merged, and I pulled the code explicitly.

The extensions seem to be working now. It seems that what did it was removing the web app's data. Before, even when I uninstalled and reinstalled the extension, it remembered that I shouldn't be using it. 

Thanks for the suggestion!

**Comment by gyaneesh** [comment]
@xthursdayx wanna take the time out to appreciate your contributions you've made so far!

> Would this qualify as "repackaging" or "redistributing" changes? If so, it seems that some extensions (eg: TokenVault) do not allow that. From the thread you linked:
> 
> > Note that TokenVault does not have a redistribution license so repackaging that and redistributing it to other users is not fair use.
> 
> Mostly, though: thank you for this! The recent client changes have broken quite a few of my extensions, and your write-up has allowed me to work around the issues for the editors I care about most.

This was my initial thought as well, if we were to approach by renaming the package identifiers the first part denotes the "fully qualified domain name" of the organization and I have a strong feeling this could possible breach the code of conduct. If our only approach is to rename the package IDs, my idea would be to randomly generate package IDs these extensions (whitelist maybe?) while the extensions are pulled from source and self-hosted repo is built. This shouldn't be essentially hard to implement, it's just that I'm currently in-between things so I'd pick setup some time for this.

**Comment by gyaneesh** [comment]
@xthursdayx checkout the new changes and let me know how it goes. I was not able to completely test the frontend

**Comment by xthursdayx** [comment]
> @xthursdayx checkout the new changes and let me know how it goes. I was not able to completely test the frontend

Will do.

**Comment by gyaneesh** [comment]
@xthursdayx with the new changes, we'll be masking the standardnotes's extensions ids on the fly into index.json. This way we wouldn't need to change the ids of Standard note's extension. If you could revert these, this PR should be fine to merge. Much appreciated.

**Comment by xthursdayx** [comment]
Sounds good, I'll do that. I've been testing this today though and two issues I've noticed are: 
1) [This commit](https://github.com/iganeshk/standardnotes-extensions/commit/fb0463a5287aebfa84ca43997450361dab6e2320) removed the updates to the NGINX snippet in the README that were added when my previous PR https://github.com/iganeshk/standardnotes-extensions/pull/34 was merged. I can add them back in the README.md from my branch linked to this PR if that works. 
2) For some reason the `build_repo.py` is throwing the following errors:
```
⚠️ WARNING: Unable to locate standard notes extensions list file, make sure you've cloned the source repository properly

You may encounter issues registering extensions, checkout
https://github.com/standardnotes/desktop/issues/789 for more details

Traceback (most recent call last):
File "/build/build_repo.py", line 337, in <module>
main()
File "/build/build_repo.py", line 333, in main
parse_extensions(base_dir, extensions_dir, public_dir, base_url, stdnotes_ext_list_path, ghub_headers)
File "/build/build_repo.py", line 192, in parse_extensions
if extfile in std_ext_list:
TypeError: argument of type 'NoneType' is not iterable
```
It seems to be unable to find the `stdnotes_ext_list_path` I was just beginning to look at the code to see if I could figure out why this is, but do you happen to know why this might be happening and/or are you running into this issue?

**Comment by gyaneesh** [comment]
> Sounds good, I'll do that. I've been testing this today though and two issues I've noticed are:
> 
> 1. [This commit](https://github.com/iganeshk/standardnotes-extensions/commit/fb0463a5287aebfa84ca43997450361dab6e2320) removed the updates to the NGINX snippet in the README that were added when my previous PR [Update NGINX snippet #34](https://github.com/iganeshk/standardnotes-extensions/pull/34) was merged. I can add them back in the README.md from my branch linked to this PR if that works.

👌

> 2. For some reason the `build_repo.py` is throwing the following errors:
> 
> ```
> ⚠️ WARNING: Unable to locate standard notes extensions list file, make sure you've cloned the source repository properly
> 
> 
> It seems to be unable to find the `stdnotes_ext_list_path` I was just beginning to look at the code to see if I could figure out why this is, but do you happen to know why this might be happening and/or are you running into this issue?

So this https://github.com/iganeshk/standardnotes-extensions/blob/master/standardnotes-extensions-list.txt file (list) was added with the fb0463a5287aebfa84ca43997450361dab6e2320. Make sure you're local file system has this file, this list is used to modify the package ids

**Comment by xthursdayx** [comment]
> So this https://github.com/iganeshk/standardnotes-extensions/blob/master/standardnotes-extensions-list.txt file (list) was added with the [fb0463a](https://github.com/iganeshk/standardnotes-extensions/commit/fb0463a5287aebfa84ca43997450361dab6e2320). Make sure you're local file system has this file, this list is used to modify the package ids

Right, just after posting that I realized that I need to mount `/standardnotes-extensions-list.txt` to `/build/standardnotes-extensions-list.txt` when running the docker container. I have updated the README accordingly. 

Everything appears to be working now if you want to merge.

**Pull request merged**
