### PR TITLE
Added Dockerfile and notes on running via docker, or docker-compose

### LINKED ISSUE #8: Please add this to dockerhub and put docker-compose instructions here
Would really love that. I dont have possibility to build/clone/make etc.. on my NAS. It only has docker and I run everything there including standardnotes.

Thank You!

### PR DESCRIPTION
**Pull request by mtoohey31**
This is intended to close #8, though the container still needs to be added to docker hub in order for it to be completely closed. Let me know if you'd like me to push the container, or if you'll handle it.

### CODE REVIEW

**Comment by mtoohey31** [comment]
Oh, also I added a nord theme that was created a week or two ago: https://github.com/lzambarda/sn-nord-theme

**Comment by GitJamz** [comment]
so.. what happend here? has this been added to dockerhub? if so where is the link? Can not find it there

**Comment by mtoohey31** [comment]
I haven't added it, I guess I left it as an open question in my PR comment and it never got addressed. If you'd like to add it, go for it, otherwise if nobody else is going to, I can get it done maybe sometime next week.

**Comment by GitJamz** [comment]
> I haven't added it, I guess I left it as an open question in my PR comment and it never got addressed. If you'd like to add it, go for it, otherwise if nobody else is going to, I can get it done maybe sometime next week.

Sorry Buddy i have no idea how to do that... im no poweruser at all..
Please let us know when you have added it to docker hub. Please ping me specifically

**Comment by mtoohey31** [comment]
@GitJamz it's up: https://hub.docker.com/r/mtoohey/standardnotes-extensions, instructions are in that readme on docker hub, and also in this repo's readme.

Edit: let me know if you need a different architecture that I don't have up there and I can try to build for that too, I think I covered most of what should be necessary though.

**Pull request merged**
